version: '3'

services:
    db:
      image: mongo:5
      restart: always
      ports:
        - 27017:27017
      environ ment:
        MONGODB_DATABASE: nest-pokemon
      volumes:
        - ./mongo:/data/db
